# Generated by Django 3.2.7 on 2021-09-28 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('idTienda', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=20)),
                ('idTienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('stockActual', models.PositiveSmallIntegerField()),
                ('stockMinimo', models.PositiveSmallIntegerField()),
                ('valorUnitario', models.PositiveSmallIntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('idTienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('idMovimientos', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMovimiento', models.CharField(max_length=20)),
                ('cantidadProducto', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=10)),
                ('valorTotal', models.PositiveSmallIntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.producto')),
                ('idTienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='InicioSesion',
            fields=[
                ('idSesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.usuario')),
            ],
        ),
    ]
